### PR TITLE
Change the startup script to forward signals to the haproxy process

### PR DESCRIPTION
**Pull request by ramirogm**
to be able to support graceful stop

Change-type: minor
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>

### CODE REVIEW

**Comment by ramirogm** [comment]
Hi @ab77 this PR is about a feature we're going to use on JF to be able to perform a "handover" update of haproxy.

The script forwards the USR1 signal to haproxy so that it can perform a clean shutdown 
http://docs.haproxy.org/2.6/management.html#4

**Comment by ramirogm** [comment]
@ab77 About BoB....Do you mean testing if on the JF instance, or something more specific?

**Comment by ramirogm** [comment]
I've tested this on my fleet with a sample app, I plan to upload that as an example of how to use the handover library

**Comment by ab77** [comment]
> @ab77 About BoB....Do you mean testing if on the JF instance, or something more specific?

I mean testing anything that uses that project, I know of JF and https://github.com/balena-io/balena-cloud @ramirogm

**Comment by ramirogm** [comment]
@ab77 I've been testing this on JF, works ok forwarding the signal to haproxy; also the script monitoring the `/certs` volume triggers the reload

**Comment by ramirogm** [comment]
@balena-ci I self-certify!

**Pull request merged**
